pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Code checkout completed'
            }
        }

        stage('Build') {
            steps {
                echo 'Building application'
                dir('Spark_Demo') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Unit Test') {
            steps {
                dir('Spark_Demo') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Spark_Demo') {
                    bat 'mvn package -DskipTests'
                    archiveArtifacts artifacts: 'Spark_Demo/target/*.jar'
                }
            }
        }
    }

    post {
        success {
            echo 'Demo pipeline completed successfully'
        }
        failure {
            echo 'Demo pipeline failed'
        }
    }
}
